name: Recovery Build (Redmi 13 Moon)

on:
  workflow_dispatch:
    inputs:
      MANIFEST_URL:
        description: 'TWRP manifest URL'
        required: true
        default: 'https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp'
      MANIFEST_BRANCH:
        description: 'TWRP manifest branch'
        required: true
        default: 'twrp-14.1'
      DEVICE_TREE_URL:
        description: 'Device tree URL'
        required: true
        default: 'https://github.com/twrpdtgen/android_device_xiaomi_moon'
      DEVICE_TREE_BRANCH:
        description: 'Device tree branch'
        required: true
        default: 'twrp-14.0'
      DEVICE_PATH:
        description: 'Local device path'
        required: true
        default: 'device/xiaomi/moon'
      COMMON_TREE_URL:
        description: 'Common tree URL (optional)'
        required: false
      COMMON_PATH:
        description: 'Common tree path (optional)'
        required: false
      DEVICE_NAME:
        description: 'Codename of device'
        required: true
        default: 'moon'
      MAKEFILE_NAME:
        description: 'Makefile/lunch combo name'
        required: true
        default: 'twrp_moon'
      BUILD_TARGET:
        description: 'Build target (e.g., recovery)'
        required: true
        default: 'recovery'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
    - name: Display Input Parameters
      run: |
        echo "::group::Inputs"
        echo "Manifest URL: ${{ github.event.inputs.MANIFEST_URL }}"
        echo "Manifest Branch: ${{ github.event.inputs.MANIFEST_BRANCH }}"
        echo "Device Tree URL: ${{ github.event.inputs.DEVICE_TREE_URL }}"
        echo "Device Tree Branch: ${{ github.event.inputs.DEVICE_TREE_BRANCH }}"
        echo "Device Path: ${{ github.event.inputs.DEVICE_PATH }}"
        echo "Device Name: ${{ github.event.inputs.DEVICE_NAME }}"
        echo "Makefile Name: ${{ github.event.inputs.MAKEFILE_NAME }}"
        echo "Build Target: ${{ github.event.inputs.BUILD_TARGET }}.img"
        echo "::endgroup::"

    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Cleanup Runner
      uses: rokibhasansagar/slimhub_actions@main

    - name: Install Dependencies
      run: |
        sudo apt update && sudo apt upgrade -y
        DEBIAN_FRONTEND=noninteractive sudo apt install -yq \
          bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg \
          gperf imagemagick lib32ncurses-dev lib32readline-dev lib32z1-dev liblz4-tool \
          libncurses-dev libncurses6 libsdl1.2-dev libssl-dev libxml2 libxml2-utils \
          lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev \
          python3 python3-pip tar openjdk-11-jdk

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Setup SSH Key (if needed)
      if: ${{ startsWith(github.event.inputs.MANIFEST_URL, 'git@github.com') || 
              startsWith(github.event.inputs.DEVICE_TREE_URL, 'git@github.com') ||
              startsWith(github.event.inputs.COMMON_TREE_URL, 'git@github.com') }}
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: |
          ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install repo tool
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Initialize repo
      run: |
        mkdir workspace && cd workspace
        git config --global user.name "KrzysTheTech"
        git config --global user.email "example@example.com"
        repo init --depth=1 -u ${{ github.event.inputs.MANIFEST_URL }} -b ${{ github.event.inputs.MANIFEST_BRANCH }}
      id: init

    - name: Sync repo
      run: |
        repo sync -j$(nproc --all) --force-sync
      working-directory: workspace

    - name: Clone device tree
      run: |
        git clone ${{ github.event.inputs.DEVICE_TREE_URL }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ./${{ github.event.inputs.DEVICE_PATH }}
      working-directory: workspace

    - name: Clone common tree (if any)
      if: ${{ github.event.inputs.COMMON_TREE_URL && github.event.inputs.COMMON_PATH }}
      run: |
        git clone ${{ github.event.inputs.COMMON_TREE_URL }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ./${{ github.event.inputs.COMMON_PATH }}
      working-directory: workspace

    - name: Add swap space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 12

    - name: Build TWRP
      run: |
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        lunch ${{ github.event.inputs.MAKEFILE_NAME }}-eng
        make clean
        make ${{ github.event.inputs.BUILD_TARGET }}image -j$(nproc --all)
      working-directory: workspace

    - name: Upload Build Output
      uses: softprops/action-gh-release@v2
      with:
        files: |
          workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/${{ github.event.inputs.BUILD_TARGET }}.img
          workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/*.zip
          workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/*vendor*.img
        name: ${{ github.event.inputs.DEVICE_NAME }}-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: |
          Manifest Branch: ${{ github.event.inputs.MANIFEST_BRANCH }}
          Device: ${{ github.event.inputs.DEVICE_NAME }}
          Target: ${{ github.event.inputs.BUILD_TARGET }}.img
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
